numAttributes = 9; 
specificity= {'medium';'specific';'broad'};
task = {'inf'; 'notinf'; 'both'};
objective = {'resource'; 'action'};
authosen = {'yes'; 'no'};
spatialsen = {'yes'; 'no'};
timesen = {'yes'; 'no'};
polywords =  {'yes'; 'no'};
genre = {'reference';'news';'business';'community'};
topic = {
    'Adults-Sex';
    'Arts-Culture';
    'Finance';
    'Cars-Transportation';
    'Computers-Internet';
    'Education';
    'Entertainment-Music-Games';
    'Health';
    'Home-Garden';
    'Politics-Government';
    'Religion-Belief-Systems';
    'Science-Mathematics';
    'Social-Science';
    'Sports';
    'Technology-Electronic';
    'Travel';
    'Beauty-Style';
    'Industrial-Goods-Services';
    'Undefined';
    'Work';
    'Food-Drink';
    'Charity';
    'Person'};

attrsNumVals = {3; 3; 2; 2; 2; 2; 2; 4; 23};
attributes = {specificity; task; objective; authosen; spatialsen;
timesen; polywords; genre; topic}; 
attrNames = {'specificity'; 'task'; 'objective'; 'authosen'; 'spatialsen'; 'timesen'; 'polywords'; 'genre'; 'topic' };
pcAttrNames = {'specificity'; 'task'; 'objective'; 'author s.'; 'spatial s.'; 'time s.'; 'scope'; 'genre'; 'topic' };