figure; 
msize = 3;
lwidth=6; 
fsize = 20; 
load ../wnNgbr.txt;
wn = wnNgbr;
plot(wn(:, 1), wn(:, 2), 'b-*' ,'LineWidth', lwidth ,'MarkerSize', msize, 'MarkerFaceColor', [ 0 0 1]); 
expWnVal = sum(wn(:, 1).* wn(:, 2))/sum(wn(:, 2));
legend('Experiment');
set(gca, 'FontSize', 15);
grid on; 
hold on;
xlabel('Number of neighbours', 'FontSize', fsize);
ylabel('Number of words', 'FontSize', fsize);
yl = get(gca, 'Ylim');
al = [yl(1):yl(2)];
len = length(al);
bl = expWnVal* ones(1, len);
plot(bl, al, 'r--','LineWidth', lwidth);
m = sprintf('avg = %g', expWnVal); 
text(expWnVal+0.5, (yl(2)-yl(1))*0.75, m, 'HorizontalAlignment', 'left', 'FontSize', 15);    
% title('Number of related words in WN for given query word'); 
print(gcf, '-dpng', 'ngbr');
saveas(gcf, 'ngbr', 'fig'); 