* FastQ

Code for fast scalable multi-facet intent classification of web search queries using dynamically constructed tree-structured graphical models. 
This code incorporates (Euro) WordNet, thus exploiting the semantic relationships in the lexicon to improve the classification results.

* Dependencies
- WordNet (integrated into a MySQL) http://wordnet.princeton.edu/, http://www.illc.uva.nl/EuroWordNet/
- libdai http://people.kyb.tuebingen.mpg.de/jorism/libDAI/
- matlab (For plotting results. see mcode/ sub-directory)

* Compilation

To compile, goto src/ and run make. The following paths need to be edited
for correct compilation: 
 
WN_ROOT=/usr/local/WordNet-3.0
DAI_ROOT=${HOME}/Code/libdai

Optional - Only main.cpp uses matlab headers. Present iteration of the
code has this commented out. 

MATLAB_ROOT=/chalmers/sw/sup/matlab-2009b

TODO autoconf/automake

** Running on Linux

On njlaptop: If the path does not work, add to path the following: /

** Running on Mac

- See details of configuring for mac on http://developer.apple.com/internet/opensource/osdb.html
- If installing from port, the default location changes to /opt/local/
   - /opt/local/var/run
   - /opt/local/share/mysql5 

